INSERT INTO cities (name, department_id) SELECT 'Almaguer', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Argelia', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Balboa', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Bolívar', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Buenos Aires', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Cajibío', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Caldono', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Caloto', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Corinto', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'El Tambo', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Florencia', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Guachené', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Guapí', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Inzá', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Jambaló', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'La Sierra', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'La Vega', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'López de Micay', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Mercaderes', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Miranda', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Morales', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Padilla', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Páez', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Patía', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Piamonte', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Piendamó', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Popayán', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Puerto Tejada', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Puracé', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Rosas', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'San Sebastián', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Santa Rosa', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Santander de Quilichao', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Silvia', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Sotará', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Suárez', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Sucre', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Timbío', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Timbiquí', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Toribío', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Totoró', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Villa Rica', id FROM dept;
WITH dept AS (INSERT INTO departments (name) VALUES ('Cesar') ON CONFLICT (name) DO UPDATE SET name = EXCLUDED.name RETURNING id)
INSERT INTO cities (name, department_id) SELECT 'Aguachica', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Agustín Codazzi', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Astrea', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Becerril', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Bosconia', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Chimichagua', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Chiriguaná', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Curumaní', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'El Copey', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'El Paso', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Gamarra', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'González', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'La Gloria (Cesar)', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'La Jagua de Ibirico', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'La Paz', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Manaure Balcón del Cesar', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Pailitas', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Pelaya', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Pueblo Bello', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Río de Oro', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'San Alberto', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'San Diego', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'San Martín', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Tamalameque', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Valledupar', id FROM dept;
WITH dept AS (INSERT INTO departments (name) VALUES ('Chocó') ON CONFLICT (name) DO UPDATE SET name = EXCLUDED.name RETURNING id)
INSERT INTO cities (name, department_id) SELECT 'Acandí', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Alto Baudó', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Bagadó', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Bahía Solano', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Bajo Baudó', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Bojayá', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Cantón de San Pablo', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Cértegui', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Condoto', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'El Atrato', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'El Carmen de Atrato', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'El Carmen del Darién', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Istmina', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Juradó', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Litoral de San Juan', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Lloró', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Medio Atrato', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Medio Baudó', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Medio San Juan', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Nóvita', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Nuquí', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Quibdó', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Río Iró', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Río Quito', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Riosucio', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'San José del Palmar', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Sipí', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Tadó', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Unión Panamericana', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Unguía', id FROM dept;
WITH dept AS (INSERT INTO departments (name) VALUES ('Cundinamarca') ON CONFLICT (name) DO UPDATE SET name = EXCLUDED.name RETURNING id)
INSERT INTO cities (name, department_id) SELECT 'Agua de Dios', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Albán', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Anapoima', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Anolaima', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Apulo', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Arbeláez', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Beltrán', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Bituima', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Bogotá', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Bojacá', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Cabrera', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Cachipay', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Cajicá', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Caparrapí', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Cáqueza', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Carmen de Carupa', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Chaguaní', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Chía', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Chipaque', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Choachí', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Chocontá', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Cogua', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Cota', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Cucunubá', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'El Colegio', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'El Peñón', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'El Rosal', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Facatativá', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Fómeque', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Fosca', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Funza', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Fúquene', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Fusagasugá', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Gachalá', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Gachancipá', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Gachetá', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Gama', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Girardot', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Granada', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Guachetá', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Guaduas', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Guasca', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Guataquí', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Guatavita', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Guayabal de Síquima', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Guayabetal', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Gutiérrez', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Jerusalén', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Junín', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'La Calera', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'La Mesa', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'La Palma', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'La Peña', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'La Vega', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Lenguazaque', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Machetá', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Madrid', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Manta', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Medina', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Mosquera', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Nariño', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Nemocón', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Nilo', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Nimaima', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Nocaima', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Pacho', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Paime', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Pandi', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Paratebueno', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Pasca', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Puerto Salgar', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Pulí', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Quebradanegra', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Quetame', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Quipile', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Ricaurte', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'San Antonio del Tequendama', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'San Bernardo', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'San Cayetano', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'San Francisco', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'San Juan de Rioseco', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Sasaima', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Sesquilé', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Sibaté', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Silvania', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Simijaca', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Soacha', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Sopó', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Subachoque', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Suesca', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Supatá', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Susa', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Sutatausa', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Tabio', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Tausa', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Tena', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Tenjo', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Tibacuy', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Tibirita', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Tocaima', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Tocancipá', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Topaipí', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Ubalá', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Ubaque', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Ubaté', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Une', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Útica', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Venecia', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Vergara', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Vianí', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Villagómez', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Villapinzón', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Villeta', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Viotá', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Yacopí', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Zipacón', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Zipaquirá', id FROM dept;
WITH dept AS (INSERT INTO departments (name) VALUES ('Córdoba') ON CONFLICT (name) DO UPDATE SET name = EXCLUDED.name RETURNING id)
INSERT INTO cities (name, department_id) SELECT 'Ayapel', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Buenavista', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Canalete', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Cereté', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Chimá', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Chinú', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Ciénaga de Oro', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Cotorra', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'La Apartada', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Lorica', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Los Córdobas', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Momil', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Montelíbano', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Montería', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Moñitos', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Planeta Rica', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Pueblo Nuevo', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Puerto Escondido', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Puerto Libertador', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Purísima', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Sahagún', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'San Andrés de Sotavento', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'San Antero', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'San Bernardo del Viento', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'San Carlos', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'San José de Uré', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'San Pelayo', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Tierralta', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Tuchín', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Valencia', id FROM dept;
WITH dept AS (INSERT INTO departments (name) VALUES ('Guainía') ON CONFLICT (name) DO UPDATE SET name = EXCLUDED.name RETURNING id)
INSERT INTO cities (name, department_id) SELECT 'Inírida', id FROM dept;
WITH dept AS (INSERT INTO departments (name) VALUES ('Guaviare') ON CONFLICT (name) DO UPDATE SET name = EXCLUDED.name RETURNING id)
INSERT INTO cities (name, department_id) SELECT 'Calamar', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'El Retorno', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Miraflores', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'San José del Guaviare', id FROM dept;
WITH dept AS (INSERT INTO departments (name) VALUES ('Huila') ON CONFLICT (name) DO UPDATE SET name = EXCLUDED.name RETURNING id)
INSERT INTO cities (name, department_id) SELECT 'Acevedo', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Agrado', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Aipe', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Algeciras', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Altamira', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Baraya', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Campoalegre', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Colombia', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'El Pital', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Elías', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Garzón', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Gigante', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Guadalupe', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Hobo', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Íquira', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Isnos', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'La Argentina', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'La Plata', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Nátaga', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Neiva', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Oporapa', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Paicol', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Palermo', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Palestina', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Pitalito', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Rivera', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Saladoblanco', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'San Agustín', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Santa María', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Suaza', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Tarqui', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Tello', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Teruel', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Tesalia', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Timaná', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Villavieja', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Yaguará', id FROM dept;
WITH dept AS (INSERT INTO departments (name) VALUES ('La Guajira') ON CONFLICT (name) DO UPDATE SET name = EXCLUDED.name RETURNING id)
INSERT INTO cities (name, department_id) SELECT 'Albania', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Barrancas', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Dibulla', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Distracción', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'El Molino', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Fonseca', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Hatonuevo', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'La Jagua del Pilar', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Maicao', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Manaure', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Riohacha', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'San Juan del Cesar', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Uribia', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Urumita', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Villanueva', id FROM dept;
WITH dept AS (INSERT INTO departments (name) VALUES ('Magdalena') ON CONFLICT (name) DO UPDATE SET name = EXCLUDED.name RETURNING id)
INSERT INTO cities (name, department_id) SELECT 'Algarrobo', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Aracataca', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Ariguaní', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Cerro de San Antonio', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Chibolo', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Chibolo', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Ciénaga', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Concordia', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'El Banco', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'El Piñón', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'El Retén', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Fundación', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Guamal', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Nueva Granada', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Pedraza', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Pijiño del Carmen', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Pivijay', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Plato', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Pueblo Viejo', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Remolino', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Sabanas de San Ángel', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Salamina', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'San Sebastián de Buenavista', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'San Zenón', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Santa Ana', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Santa Bárbara de Pinto', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Santa Marta', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Sitionuevo', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Tenerife', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Zapayán', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Zona Bananera', id FROM dept;
WITH dept AS (INSERT INTO departments (name) VALUES ('Meta') ON CONFLICT (name) DO UPDATE SET name = EXCLUDED.name RETURNING id)
INSERT INTO cities (name, department_id) SELECT 'Acacías', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Barranca de Upía', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Cabuyaro', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Castilla la Nueva', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Cubarral', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Cumaral', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'El Calvario', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'El Castillo', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'El Dorado', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Fuente de Oro', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Granada', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Guamal', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'La Macarena', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'La Uribe', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Lejanías', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Mapiripán', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Mesetas', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Puerto Concordia', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Puerto Gaitán', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Puerto Lleras', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Puerto López', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Puerto Rico', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Restrepo', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'San Carlos de Guaroa', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'San Juan de Arama', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'San Juanito', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'San Martín', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Villavicencio', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Vista Hermosa', id FROM dept;
WITH dept AS (INSERT INTO departments (name) VALUES ('Nariño') ON CONFLICT (name) DO UPDATE SET name = EXCLUDED.name RETURNING id)
INSERT INTO cities (name, department_id) SELECT 'Aldana', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Ancuyá', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Arboleda', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Barbacoas', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Belén', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Buesaco', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Chachagüí', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Colón', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Consacá', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Contadero', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Córdoba', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Cuaspud', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Cumbal', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Cumbitara', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'El Charco', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'El Peñol', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'El Rosario', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'El Tablón', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'El Tambo', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Francisco Pizarro', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Funes', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Guachucal', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Guaitarilla', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Gualmatán', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Iles', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Imués', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Ipiales', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'La Cruz', id FROM dept;
