INSERT INTO cities (name, department_id) SELECT 'La Florida', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'La Llanada', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'La Tola', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'La Unión', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Leiva', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Linares', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Los Andes', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Magüí Payán', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Mallama', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Mosquera', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Nariño', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Olaya Herrera', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Ospina', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Pasto', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Policarpa', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Potosí', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Providencia', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Puerres', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Pupiales', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Ricaurte', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Roberto Payán', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Samaniego', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'San Bernardo', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'San José de Albán', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'San Lorenzo', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'San Pablo', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'San Pedro de Cartago', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Sandoná', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Santa Bárbara', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Santacruz', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Sapuyes', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Taminango', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Tangua', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Tumaco', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Túquerres', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Yacuanquer', id FROM dept;
WITH dept AS (INSERT INTO departments (name) VALUES ('Norte de Santander') ON CONFLICT (name) DO UPDATE SET name = EXCLUDED.name RETURNING id)
INSERT INTO cities (name, department_id) SELECT 'Ábrego', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Arboledas', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Bochalema', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Bucarasica', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Cáchira', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Cácota', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Chinácota', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Chitagá', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Convención', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Cúcuta', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Cucutilla', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Duranía', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'El Carmen', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'El Tarra', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'El Zulia', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Gramalote', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Hacarí', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Herrán', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'La Esperanza', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'La Playa de Belén', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Labateca', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Los Patios', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Lourdes', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Mutiscua', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Ocaña', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Pamplona', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Pamplonita', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Puerto Santander', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Ragonvalia', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Salazar de Las Palmas', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'San Calixto', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'San Cayetano', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Santiago', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Santo Domingo de Silos', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Sardinata', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Teorama', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Tibú', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Toledo', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Villa Caro', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Villa del Rosario', id FROM dept;
WITH dept AS (INSERT INTO departments (name) VALUES ('Putumayo') ON CONFLICT (name) DO UPDATE SET name = EXCLUDED.name RETURNING id)
INSERT INTO cities (name, department_id) SELECT 'Colón', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Mocoa', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Orito', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Puerto Asís', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Puerto Caicedo', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Puerto Guzmán', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Puerto Leguízamo', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'San Francisco', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'San Miguel', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Santiago', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Sibundoy', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Valle del Guamuez', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Villagarzón', id FROM dept;
WITH dept AS (INSERT INTO departments (name) VALUES ('Quindío') ON CONFLICT (name) DO UPDATE SET name = EXCLUDED.name RETURNING id)
INSERT INTO cities (name, department_id) SELECT 'Armenia', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Buenavista', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Calarcá', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Circasia', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Córdoba', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Filandia', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Génova', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'La Tebaida', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Montenegro', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Pijao', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Quimbaya', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Salento', id FROM dept;
WITH dept AS (INSERT INTO departments (name) VALUES ('Risaralda') ON CONFLICT (name) DO UPDATE SET name = EXCLUDED.name RETURNING id)
INSERT INTO cities (name, department_id) SELECT 'Apía', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Balboa', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Belén de Umbría', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Dosquebradas', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Guática', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'La Celia', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'La Virginia', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Marsella', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Mistrató', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Pereira', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Pueblo Rico', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Quinchía', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Santa Rosa de Cabal', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Santuario', id FROM dept;
WITH dept AS (INSERT INTO departments (name) VALUES ('San Andrés y Providencia') ON CONFLICT (name) DO UPDATE SET name = EXCLUDED.name RETURNING id)
INSERT INTO cities (name, department_id) SELECT 'Providencia y Santa Catalina Islas', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'San Andrés', id FROM dept;
WITH dept AS (INSERT INTO departments (name) VALUES ('Santander') ON CONFLICT (name) DO UPDATE SET name = EXCLUDED.name RETURNING id)
INSERT INTO cities (name, department_id) SELECT 'Aguada', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Albania', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Aratoca', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Barbosa', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Barichara', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Barrancabermeja', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Betulia', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Bolívar', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Bucaramanga', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Cabrera', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'California', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Capitanejo', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Carcasí', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Cepitá', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Cerrito', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Charalá', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Charta', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Chima', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Chipatá', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Cimitarra', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Concepción', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Confines', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Contratación', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Coromoro', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Curití', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'El Carmen de Chucurí', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'El Guacamayo', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'El Peñón', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'El Playón', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'El Socorro', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Encino', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Enciso', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Florián', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Floridablanca', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Galán', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Gámbita', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Girón', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Guaca', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Guadalupe', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Guapotá', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Guavatá', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Güepsa', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Hato', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Jesús María', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Jordán', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'La Belleza', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'La Paz', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Landázuri', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Lebrija', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Los Santos', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Macaravita', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Málaga', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Matanza', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Mogotes', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Molagavita', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Ocamonte', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Oiba', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Onzaga', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Palmar', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Palmas del Socorro', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Páramo', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Piedecuesta', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Pinchote', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Puente Nacional', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Puerto Parra', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Puerto Wilches', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Rionegro', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Sabana de Torres', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'San Andrés', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'San Benito', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'San Gil', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'San Joaquín', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'San José de Miranda', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'San Miguel', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'San Vicente de Chucurí', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Santa Bárbara', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Santa Helena del Opón', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Simacota', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Suaita', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Sucre', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Suratá', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Tona', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Valle de San José', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Vélez', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Vetas', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Villanueva', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Zapatoca', id FROM dept;
WITH dept AS (INSERT INTO departments (name) VALUES ('Sucre') ON CONFLICT (name) DO UPDATE SET name = EXCLUDED.name RETURNING id)
INSERT INTO cities (name, department_id) SELECT 'Buenavista', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Caimito', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Chalán', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Colosó', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Corozal', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Coveñas', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'El Roble', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Galeras', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Guaranda', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'La Unión', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Los Palmitos', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Majagual', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Morroa', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Ovejas', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Sampués', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'San Antonio de Palmito', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'San Benito Abad', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'San Juan de Betulia', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'San Marcos', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'San Onofre', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'San Pedro', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Sincé', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Sincelejo', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Sucre', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Tolú', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Tolú Viejo', id FROM dept;
WITH dept AS (INSERT INTO departments (name) VALUES ('Tolima') ON CONFLICT (name) DO UPDATE SET name = EXCLUDED.name RETURNING id)
INSERT INTO cities (name, department_id) SELECT 'Alpujarra', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Alvarado', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Ambalema', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Anzoátegui', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Armero', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Ataco', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Cajamarca', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Carmen de Apicalá', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Casabianca', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Chaparral', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Coello', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Coyaima', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Cunday', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Dolores', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'El Espinal', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Falán', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Flandes', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Fresno', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Guamo', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Herveo', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Honda', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Ibagué', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Icononzo', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Lérida', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Líbano', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Mariquita', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Melgar', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Murillo', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Natagaima', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Ortega', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Palocabildo', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Piedras', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Planadas', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Prado', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Purificación', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Rioblanco', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Roncesvalles', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Rovira', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Saldaña', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'San Antonio', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'San Luis', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Santa Isabel', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Suárez', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Valle de San Juan', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Venadillo', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Villahermosa', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Villarrica', id FROM dept;
WITH dept AS (INSERT INTO departments (name) VALUES ('Valle del Cauca') ON CONFLICT (name) DO UPDATE SET name = EXCLUDED.name RETURNING id)
INSERT INTO cities (name, department_id) SELECT 'Alcalá', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Andalucía', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Ansermanuevo', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Argelia', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Bolívar', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Buenaventura', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Buga', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Bugalagrande', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Caicedonia', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Cali', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Calima', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Candelaria', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Cartago', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Dagua', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'El Águila', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'El Cairo', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'El Cerrito', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'El Dovio', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Florida', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Ginebra', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Guacarí', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Jamundí', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'La Cumbre', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'La Unión', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'La Victoria', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Obando', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Palmira', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Pradera', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Restrepo', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Riofrío', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Roldanillo', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'San Pedro', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Sevilla', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Toro', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Trujillo', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Tuluá', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Ulloa', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Versalles', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Vijes', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Yotoco', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Yumbo', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Zarzal', id FROM dept;
WITH dept AS (INSERT INTO departments (name) VALUES ('Vaupés') ON CONFLICT (name) DO UPDATE SET name = EXCLUDED.name RETURNING id)
INSERT INTO cities (name, department_id) SELECT 'Carurú', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Mitú', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Taraira', id FROM dept;
WITH dept AS (INSERT INTO departments (name) VALUES ('Vichada') ON CONFLICT (name) DO UPDATE SET name = EXCLUDED.name RETURNING id)
INSERT INTO cities (name, department_id) SELECT 'Cumaribo', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'La Primavera', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Puerto Carreño', id FROM dept;
INSERT INTO cities (name, department_id) SELECT 'Santa Rosalía', id FROM dept;
